# 指定运行环境
language: node_js
node_js:
  - lts/*

# 仅监控 master 分支
branches:
  only:
    - master

jobs:
  include:
    - name: "Github Pages"
      install:
        - yarn install
      before_script:
        - git clone -b gh-pages https://${GITHUB_REPOSITORY}
      script:
        - yarn build
      after_success:
        - cp -r lin-ui-doc/.git dist/.git
        - cd dist
        - git config --global user.name "Juzi"
        - git config --global user.email "juzi214032@qq.com"
        - git add -A
        - "git commit -m 'build: Travis CI automatic compilation.'"
        - if [ ${GITHUB_SWITCH} -eq 1 ]; then git push "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@${GITHUB_REPOSITORY}" ${GITHUB_BRANCH}:${GITHUB_BRANCH}; fi
    - name: "Gitee Pages"
      install:
        - yarn install
      script:
        - yarn build
      after_success:
        - cd dist
        - git init
        - git config --global user.name "Deployment Bot"
        - git config --global user.email "deploy@travis-ci.org"
        - git add -A
        - "git commit -m 'build: Travis CI automatic compilation.'"
        - if [ ${GITEE_SWITCH} -eq 1 ]; then git push -f "https://${GITEE_USERNAME}:${GITEE_TOKEN}@${GITEE_REPOSITORY}" master:${GITEE_BRANCH}; fi
    - name: "Coding Pages"
      install:
        - yarn install
      script:
        - yarn build
      before_script:
        - cd docs/.vuepress
        - sed -i "s$/lin-ui-doc/$/$" config.js
        - cd ../../
      after_success:
        - cd dist
        - git init
        - git config --global user.name "Deployment Bot"
        - git config --global user.email "deploy@travis-ci.org"
        - git add -A
        - "git commit -m 'build: Travis CI automatic compilation.'"
        - if [ ${CODING_SWITCH} -eq 1 ]; then git push -f "https://${CODING_USERNAME}:${CODING_TOKEN}@${CODING_REPOSITORY}" master:${CODING_BRANCH}; fi
