# 指定运行环境
language: node_js
node_js:
  - lts/*

# 仅监控 master 分支
branches:
  only:
    - master
    - develop
    - /^gh-pages-.*$/

jobs:
  include:
    - name: "Code Async"
      if: branch = master
      install: skip
      script: skip
      after_success:
        - if [ ${GITEE_SWITCH} -eq 1 ]; then git push -f "https://${GITEE_USERNAME}:${GITEE_TOKEN}@${GITEE_REPOSITORY}" master; fi
        - if [ ${CODING_SWITCH} -eq 1 ]; then git push -f "https://${CODING_USERNAME}:${CODING_TOKEN}@${CODING_REPOSITORY}" master; fi
    - name: "Github Pages"
      if: branch = master
      install: yarn install
      before_script: git clone -b ${GITHUB_BRANCH} https://${GITHUB_REPOSITORY}
      script: yarn build
      after_success:
        - cp -r lin-ui-doc/.git dist/.git
        - cd dist
        - git config --global user.name "Juzi"
        - git config --global user.email "juzi214032@qq.com"
        - git add -A
        - "git commit -m 'build: Travis CI automatic compilation.'"
        - if [ ${GITHUB_SWITCH} -eq 1 ]; then git push "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@${GITHUB_REPOSITORY}" ${GITHUB_BRANCH}; fi
    - name: "Gitee Pages"
      if: branch = master
      install: yarn install
      before_script:
        - git clone -b gh-pages https://${GITEE_REPOSITORY}
      script: yarn build
      after_success:
        - cp -r lin-ui-doc/.git dist/.git
        - cd dist
        - git config --global user.name "Juzi"
        - git config --global user.email "juzi214032@qq.com"
        - git add -A
        - "git commit -m 'build: Travis CI automatic compilation.'"
        - if [ ${GITEE_SWITCH} -eq 1 ]; then git push "https://${GITEE_USERNAME}:${GITEE_TOKEN}@${GITEE_REPOSITORY}" ${GITEE_BRANCH}; fi
    - name: "Coding Pages"
      if: branch = master
      install: yarn install
      before_script:
        - git clone -b gh-pages https://e.coding.net/juzi214032/lin-ui-doc.git
        - cd docs/.vuepress
        - sed -i "s$/lin-ui-doc/$/$" config.js
        - cd ../../
      script: yarn build
      after_success:
        - cp -r lin-ui-doc/.git dist/.git
        - cd dist
        - git config --global user.name "Juzi"
        - git config --global user.email "juzi214032@qq.com"
        - git add -A
        - "git commit -m 'build: Travis CI automatic compilation.'"
        - if [ ${CODING_SWITCH} -eq 1 ]; then git push "https://${CODING_USERNAME}:${CODING_TOKEN}@${CODING_REPOSITORY}" ${CODING_BRANCH}; fi
        - if [ ${GITHUB_SWITCH} -eq 1 ]; then git push "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@${GITHUB_REPOSITORY}" head:server; fi
    - name: "Test Doc"
      if: branch =~ ^gh-pages-.*$
      install: yarn install
      before_script:
        - cd docs/.vuepress
        - sed -i "s$/lin-ui-doc/$/$" config.js
        - cd ../../
      script: yarn build
      after_success:
        - cd dist
        - git init
        - git config --global user.name "Juzi"
        - git config --global user.email "juzi214032@qq.com"
        - git add -A
        - "git commit -m 'build: Travis CI automatic compilation.'"
        - git checkout -b $TRAVIS_BRANCH
        - git push -f "https://${CODING_USERNAME}:${CODING_TOKEN}@${CODING_REPOSITORY}" $TRAVIS_BRANCH
    - name: "Develop Doc"
      if: branch = develop
      install: yarn install
      before_script:
        - git clone -b gh-pages-develop https://e.coding.net/juzi214032/lin-ui-doc.git
        - cd docs/.vuepress
        - sed -i "s$/lin-ui-doc/$/$" config.js
        - cd ../../
      script: yarn build
      after_success:
        - cp -r lin-ui-doc/.git dist/.git
        - cd dist
        - git init
        - git config --global user.name "Juzi"
        - git config --global user.email "juzi214032@qq.com"
        - git add -A
        - "git commit -m 'build: Travis CI automatic compilation.'"
        - git checkout -b $TRAVIS_BRANCH
        - git push "https://${CODING_USERNAME}:${CODING_TOKEN}@${CODING_REPOSITORY}" gh-pages-develop

