name: 自动编译

on: [push]

jobs:
  build_root:
    name: VuePress 编译_根路径
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: 安装 Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: 安装 NPM 依赖
        run: npm i
      - name: 开始编译
        run: npm run build
  build_se_level:
    name: VuePress 编译_二级目录
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: 安装 Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: 安装 NPM 依赖
        run: npm i
      - name: 修改编译路径
        run: sed -i "s$base:'/',$base:'/lin-ui-doc/',$" docs/.vuepress/config.js
      - name: 开始编译
        run: npm run build

  auto_release:
    name: 自动发布
    runs-on: ubuntu-latest
    needs: build_root
    steps:
      - name: 部署上传
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
